spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/microservicesDB
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    producer:
      key-serializer: org.apache.kafka.comon.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8091
