spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: microservicesDB
      username: admin
      password: password
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:29092, localhost:29093
    consumer:
      group-id: notificationService
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
#      TODO: поменять на фактический пакет
      spring.json.trusted.packages: "*"

server:
  port: 8093