spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: microservicesDB
      username: admin
      password: password
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:29092, localhost:29093
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081

server:
  port: 8093