version: '3.8'

services:
  #TODO: разобраться с KAFKA
  kafka-1:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-1
    ports:
      - "29092:29092"
    environment:
      CLUSTER_ID: 23E8A94D28A84F6AAF6CAF78CE023F68
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      #INTERNAL - общение сервисов и кафки внутри docker-сети
      #EXTERNAL - для внешнего подключения
      #CONTROLLER - для внутренного обзения брокеров кафки между собой
      KAFKA_LISTENERS: INTERNAL://:9091, EXTERNAL://:29092, CONTROLLER://:9093
      #Все ноды внутри одного брокера
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9091,EXTERNAL://localhost:29092
      #Шифрование отсутствует
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - microservices-network

  kafka-2:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-2
    ports:
      - "29093:29093"
    environment:
      CLUSTER_ID: 23E8A94D28A84F6AAF6CAF78CE023F68
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker, controller
      #INTERNAL - общение сервисов и кафки внутри docker-сети
      #EXTERNAL - для внешнего подключения
      #CONTROLLER - для внутренного обзения брокеров кафки между собой
      KAFKA_LISTENERS: INTERNAL://:9091, EXTERNAL://:29093, CONTROLLER://:9093
      #Все ноды внутри одного брокера
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9091,EXTERNAL://localhost:29093
      #Шифрование отсутствует
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - microservices-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    depends_on:
      - kafka-1
      - kafka-2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - microservices-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - kafka-2
      - schema-registry
    ports:
      - "8086:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9091,kafka-2:9091
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - microservices-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: microservicesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data #том для сохранения данных контейнером
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: microservicesDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u admin -p password --authenticationDatabase admin --eval 'db.runCommand({ping:1})'"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8090:8090"
    networks:
      - microservices-network

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8091:8091"
    networks:
      - microservices-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres-db
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  inventory-service:
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "8092:8092"
    networks:
      - microservices-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres-db
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8093:8093"
    networks:
      - microservices-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_HOST: mongo-db
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    container_name: order-service
    ports:
      - "8094:8094"
    networks:
      - microservices-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres-db
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    ports:
      - "8095:8095"
    networks:
      - microservices-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_HOST: mongo-db

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "8096:8096"
    networks:
      - microservices-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres-db
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091,kafka-2:9091
      SCHEMA_REGISTRY_URL: http://schema-registry:8081


networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data: