plugins {
	id 'org.springframework.boot'
}

repositories {
	mavenCentral()
	maven {
		url 'https://packages.confluent.io/maven/'
	}
}

dependencies {
	//gRPS
	implementation 'org.springframework.boot:spring-boot-starter-grpc-server'
	//JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	//REST
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	// Liquibase
	implementation 'org.liquibase:liquibase-core'
	//KAFKA
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.apache.kafka:kafka-clients:3.6.0'
	//AVRO
//	implementation 'io.confluent:kafka-avro-serializer:7.7.0'
//	implementation 'org.apache.avro:avro:1.11.3'
	//PostgreSQL
	runtimeOnly 'org.postgresql:postgresql'

	//Tests(jdbc, grpc, kafka)
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-grpc-server-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

