spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/microservicesDB
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      group-id: userService
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "ru.microservices.common_events.*"



server:
  port: 8096