plugins {
	id 'org.springframework.boot'
}

dependencies {
	//KAFKA
	implementation 'org.springframework.kafka:spring-kafka'
	implementation 'org.apache.kafka:kafka-clients:3.6.0'


	//Tests (kafka)
	testImplementation 'org.springframework.kafka:spring-kafka-test'
	testImplementation 'org.testcontainers:kafka:1.19.3'
}

tasks.named('test') {
	useJUnitPlatform()
}
