spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/microservicesDB
    username: postgres
    password: password

server:
  port: 8092
